server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
  exception-handling:
    default-custom-exception-status: 200
    include-http-status: true
    http-status-mapping:
      'javax.validation.ConstraintViolationException': 400
spring:
  main:
    lazy-initialization: false
  application:
    admin:
      enabled: true


  jpa:
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true