spring:
  main:
    web-application-type: REACTIVE
  r2dbc:
    url: r2dbc:postgresql://localhost/pfk
    username: postgres
  liquibase:
    url: jdbc:postgresql://localhost/pfk

logging.level:
  liquibase: DEBUG
  org:
    springframework:
      boot:
        autoconfigure:
          liquibase: DEBUG
      r2db: DEBUG

      data: TRACE